### ISSUE TITLE
XamlFlair.WPF 1.2.13 not animating Fadeout

### ISSUE THREAD

**Issue by zaitsman** [XamlFlair/XamlFlair#101]
I copied the code from the Readme.md part that talks about `CombinedBinding` like so:

```
<Rectangle
               xf:Animations.CombinedBinding="{Binding ElementName=mainWindow, Path=DataContext.IsVisible}"
           xf:Animations.Primary="{xf:Animate BasedOn={StaticResource FadeIn}, Event=None, Duration=1500}"
           xf:Animations.Secondary="{xf:Animate BasedOn={StaticResource FadeOut}, Event=None, Duration=1500}"
           xf:Animations.StartWith="{StaticResource FadeOut}"
                Fill="Red"
            ></Rectangle>
```

When my `IsVisible` turns true then, indeed, i see FadeIn. 
When it turns false, the rectangle is immediately invisible with no animation.

I am on WPF .Net 6, VS 2022, Win 10 21H1 (19043.1526).

**Comment by assassin316** [comment]
@zaitsman  I will try this out and let you know my findings. Thanks for bringing this up.

**Comment by assassin316** [comment]
@zaitsman  I remember this, you're not the first to bring this up, it's a WPF thing. Simply use the following on your rectangle:

`xf:Animations.AllowOpacityReset="False"`

You can find more info about it [here](https://github.com/XamlFlair/XamlFlair#using-the-allowopacityreset-property-wpf-only).

**Comment by zaitsman** [comment]
Thanks heaps @assassin316  that worked!

**Comment by lszczygielek** [comment]
I spent about 2 hours setting up FadeIn and next FadeOut animation, and `xf:Animations.AllowOpacityReset="False"` helped solve it. I see it in the readme, but when you try the library the first time it is hard to correlate the issue with a solution.

**Comment by assassin316** [comment]
@lszczygielek  can you provide me a quick sample code here, I'd like to reproduce your issue.
