### ISSUE TITLE
How can I get documentation?

### ISSUE THREAD

**Issue by Gioone** [XamlFlair/XamlFlair#105]
It seems good, but I still don't know how to use XamlFlair. Is there some readable documentation for XamlFlair?

**Comment by assassin316** [comment]
Start with:

https://github.com/XamlFlair/XamlFlair#usage

Then make sure to add your ResourceDictionary to hold all your base animations:

https://github.com/XamlFlair/XamlFlair#using-a-resourcedictionary-for-base-settings

Finally start plugging them into your UI components (this shows a simple example of the best way to incorporate it):

https://github.com/XamlFlair/XamlFlair#overriding-values

**Comment by assassin316** [comment]
I haven't made an update in awhile, I'm currently building a new sample for this library, and applying upgrades to the Uno package. Hope to have these out within a month.
