### ISSUE TITLE
How to disable the mouse-over effect for the AnimatedListView item?

### ISSUE THREAD

**Issue by raminmjj** [XamlFlair/XamlFlair#106]
Hi.
How can I disable the effect in WPF version?

![image](https://user-images.githubusercontent.com/991847/209386550-8b1cd86a-9159-40da-a9ea-9e3ae80a22bd.png)

**Comment by XamlFlair** [comment]
@raminmjj  Can you clarify? Do you mean the selectionhighlight?  If so I'm not sure that relates to XamlFlair, but maybe i'm misunderstanding. Sorry for the delay, I'll be less responsive during the holiday period.

**Comment by raminmjj** [comment]
Thank you @XamlFlair
No, I mean exactly the mouse-over effect on an item on a list.
As shown in the GIF in ReadMe of this repository, no effect is seen when the mouse cursor moves over the user places items.
I implemented the sample code similar to the "user places" section. However, the result is not the same as that in the "user places" section.
Have a great holiday, and thank you again.

**Comment by assassin316** [comment]
@raminmjj Have you tried some of the properties set on the ListViewItem style ??

https://github.com/XamlFlair/XamlFlair/blob/master/Samples/XamlFlair.Samples.WPF/Styles/Controls/ListViewItem.xaml

**Comment by raminmjj** [comment]
Thank you @assassin316
