### ISSUE TITLE
CompoundSettings not working

### ISSUE THREAD

**Issue by byrialsen** [XamlFlair/XamlFlair#34]
Hi

Im trying out XamlFlair and think I found a problem with compound animation that should repeat forever. Here is my xaml code

```csharp
<Image
  Height="100"
  Margin="20,8,60,8"
  xf:Animations.Primary="{StaticResource TestCompound}"
  xf:Animations.IterationBehavior="Forever"
  Source="/Assets/Logo.png" />
```
```csharp
<xf:CompoundSettings x:Key="TestCompound">
  <xf:CompoundSettings.Sequence>

    <!--  show / fade in  -->
    <xf:AnimationSettings Delay="1000" Kind="FadeFrom" Opacity="0" Duration="2000" />

    <!-- rotate -->
    <xf:AnimationSettings Kind="RotateTo" Rotation="360" Duration="2000" />

    <!--  hide / fade out  -->
    <xf:AnimationSettings Delay="10000" Kind="FadeTo" Opacity="0" />

  </xf:CompoundSettings.Sequence>
</xf:CompoundSettings>
```
The first run seems to work perfect. The logo fades in (becomes visible), then rotated, and finally fade out (gets hidden) again. Then it starts all over but now I will never see the rotate animation anymore.

**Comment by XamlFlair** [comment]
Thanks for reporting this issue @byrialsen. What platform are you using?

**Comment by XamlFlair** [comment]
I was able to reproduce it. The reason this happens is because your logo stays at a 360 rotation, so on the 2nd time the animation repeats, it will animate from 360 to 360, so nothing happens. Your fade works because you bring it back to 0. Add this step to do an immediate reset on the rotation while it is faded out. Add it as the last step in your sequence:

	
	<xf:AnimationSettings Kind="RotateTo"
		Rotation="0"
		Duration="1" />

**Comment by byrialsen** [comment]
Thanks @XamlFlair for a quick explanation. It makes perfectly sense and I just tested that it works.
