### ISSUE TITLE
Support for Layout transformation

### ISSUE THREAD

**Issue by luisllamasbinaburo** [XamlFlair/XamlFlair#39]
Hello,

Animations currently use RenderTransformation, that is faster than Layout transformation and allow more animations, but doesn't change the other elements in the UI

I agree that this should be the normal behavior, but I found interesting to allow user to change to Layout transformation.

For example, 
Using render transformation
![render-slide](https://www.luisllamas.es/render-slide.gif)

Using layout transformation
![transform-slide](https://www.luisllamas.es/slide.gif)

I have been testing in a simple way to allow user to change transformation. I have created a new `DependendyProperty TransformProperty` in AnimationSettings, with two options: Render (default) and Layout

Then, it could be use in your app that way
```xaml
<Border xf:Animations.Primary="{xf:Animate BasedOn={StaticResource ScaleFromLeft}, Transform=Layout}">
```

What do you think?

**Comment by XamlFlair** [comment]
Yes, this would definitely help for WPF devs (since UWP doesn't have this feature). If this is easy for you to add, then go right ahead. You can also update the Readme with info for this and specify it's only for WPF.
