### ISSUE TITLE
Upgrade to support Uno 2.4.4

### ISSUE THREAD

**Issue by rdagglis** [XamlFlair/XamlFlair#47]
Currently an error occurs if a project upgrades to Uno 2.4.4

C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error MT2101: Can't resolve the reference 'Windows.UI.Xaml.DependencyProperty Windows.UI.Xaml.Media.GradientBrush::get_GradientStopsProperty()', referenced from the method 'System.Object UnoApp.MetadataBuilder_585::GetGradientStops(System.Object,System.Nullable`1<Windows.UI.Xaml.DependencyPropertyValuePrecedences>)' in 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'

**Comment by XamlFlair** [comment]
XamlFlair.Uno upgraded to use Uno.UI 2.4.4
