### ISSUE TITLE
Combined Binding doesn't work

### ISSUE THREAD

**Issue by hristowwe** [XamlFlair/XamlFlair#51]
I tried to use Combined Binding in examples but when i ran code it dosent work at all.Only primary animation appear secondary not
My code
[code.txt](https://github.com/XamlFlair/XamlFlair/files/4978981/code.txt)

So after check and uncheck my check box even first animation not work.Sorry for bad english.

**Comment by XamlFlair** [comment]
Hi @hristowwe , I've tried out your code and understand the issue. Your secondary animation does not bring back the values to their original state. Your StartWith places the Button to the "right". So secondary animation will only fade out because it's already on the "right". XamlFlair will not reset values when animations complete. so it's good practice to animate a secondary animation back towards the original values.

**Comment by hristowwe** [comment]
> Hi @hristowwe , I've tried out your code and understand the issue. Your secondary animation does not bring back the values to their original state. Your StartWith places the Button to the "right". So secondary animation will only fade out because it's already on the "right". XamlFlair will not reset values when animations complete. so it's good practice to animate a secondary animation back towards the original values.

So how can i fix that.Cam you show me example :)

**Comment by hristowwe** [comment]
Also when i use fade in and fade out it doesnt work agaon

**Comment by XamlFlair** [comment]
Hi again,

Here's some code I just tested for fade in and fade out with a checkbox:

```xml
<CheckBox x:Name="SampleCheckBox"
		  IsChecked="False"
		  Margin="214,133,540,270" />

<Button xf:Animations.CombinedBinding="{Binding IsChecked, ElementName=SampleCheckBox}"
		xf:Animations.Primary="{xf:Animate BasedOn={StaticResource FadeIn}, Event=None}"
		xf:Animations.Secondary="{xf:Animate BasedOn={StaticResource FadeOut}, Event=None}"
		xf:Animations.StartWith="{StaticResource FadeOut}"
		Margin="164,204,434,139" />
```

**Comment by XamlFlair** [comment]
@hristowwe if this works for you let me know.

**Comment by hristowwe** [comment]
fade out not work

**Comment by hristowwe** [comment]
@XamlFlair secondary animation not work

**Comment by XamlFlair** [comment]
@hristowwe  can you provide me a sample project so I can debug? Thanks.

**Comment by hristowwe** [comment]
<CheckBox x:Name="SampleCheckBox"
		  IsChecked="False"
		  Margin="214,133,540,270" />

<Button xf:Animations.CombinedBinding="{Binding IsChecked, ElementName=SampleCheckBox}"
		xf:Animations.Primary="{xf:Animate BasedOn={StaticResource FadeInAndSlideFromLeft}, Event=None}"
		xf:Animations.Secondary="{xf:Animate BasedOn={StaticResource FadeOutAndSlideToLeft}, Event=None}"
		xf:Animations.StartWith="{StaticResource FadeOutAndSlideToLeft}"
		Margin="164,204,434,139" />

this example dont work for me

**Comment by XamlFlair** [comment]
@hristowwe thanks I'll try it out and get back to you as soon as it can.

**Comment by XamlFlair** [comment]
@hristowwe  Ahhh, you're in WPF, I found your solution. you need to add:

     xf:Animations.AllowOpacityReset="False"

Read more about it here:

https://github.com/XamlFlair/XamlFlair#using-the-allowopacityreset-property-wpf-only

**Comment by hristowwe** [comment]
yes  it works nice
