### ISSUE TITLE
Compound animations not working as intended? (WPF)

### ISSUE THREAD

**Issue by msdoseightysix** [XamlFlair/XamlFlair#53]
Hello,

I have encountered an issue with the compound settings animations in my WPF application. Maybe I am just doing something wrong. I have created two compound animations, each with its individual key:

```xaml
<xf:CompoundSettings x:Key="Spin">
    <xf:CompoundSettings.Sequence>
      <xf:AnimationSettings Kind="RotateTo"
                            Rotation="360"
                            Easing="Linear"
                            Duration="1250" />
      <xf:AnimationSettings Kind="RotateFrom"
                            Rotation="0"
                            Duration="1" />
    </xf:CompoundSettings.Sequence>
  </xf:CompoundSettings>

  <xf:CompoundSettings x:Key="Pulse">
    <xf:CompoundSettings.Sequence>
      <xf:AnimationSettings Kind="FadeTo"
                            Opacity="0"
                            Duration="800" />
      <xf:AnimationSettings Kind="FadeTo"
                            Opacity="1"
                            Duration="800" />
      <xf:AnimationSettings Kind="TranslateYTo"
                            OffsetY="20"
                            Duration="300" />
      <xf:AnimationSettings Kind="TranslateYTo"
                            OffsetY="0"
                            Duration="300" />
    </xf:CompoundSettings.Sequence>
  </xf:CompoundSettings>
```
But when I use the keys on two different image controls, it seems that the animations "Spin" and "Pulse" are combined together once the second image is loaded. Here is a short GIF to show this behaviour (the blue cloud image should not rotate!)

![compound_animation](https://user-images.githubusercontent.com/19777233/89500086-61f00000-d7c1-11ea-986e-1de740281aeb.gif)

Each image control is situated on a different UserControl, the switch between the UserControl is handled by a ContentControl.
I would appreciate some help with this.

Thank you!

**Comment by XamlFlair** [comment]
@msdoseightysix  thanks for the bug report. I've been able to reproduce the issue. I will investigate it and get back to you when a fix has been applied. 👍

**Comment by XamlFlair** [comment]
@msdoseightysix  latest WPF version should have your fix 👍 Let me know when you try it.

**Comment by msdoseightysix** [comment]
I tested it with the nuget package 1.1.8 - works like a charm now!
Thank you for your fast support and keep up the good work! 👍
