### ISSUE TITLE
IterationBehavior="Forever" doesn't seem to work

### ISSUE THREAD

**Issue by jsinsel** [XamlFlair/XamlFlair#60]
I defined an animation in UWP:

`<xf:AnimationSettings x:Key="TestRotate"
                          Easing="Cubic"
                          EasingMode="EaseInOut"
                          Kind="RotateTo"
                          Rotation="360"
                          Duration="2000" />`

Then I tried using it in a control:

```
<CheckBox x:Name="SampleCheckBox"
                                  Margin="0,0,8,0"
                                  IsChecked="False" />

                        <Viewbox x:Name="kFlake"
                                 Width="20"
                                 Height="20"
                                 xf:Animations.IterationBehavior="Forever"
                                 xf:Animations.Primary="{xf:Animate BasedOn={StaticResource TestRotate},
                                                                    Event=None}"
                                 xf:Animations.PrimaryBinding="{Binding IsChecked, ElementName=SampleCheckBox}">
                            <Border Width="50"
                                    Height="50"
                                    BorderBrush="White"
                                    BorderThickness="1" />
</Viewbox>
```

There's a couple issues:
1) It only animates once, doesn't repeat forever.
2) Uncheck the checkbox doesn't stop the animation.
3) Recheck the checkbox doesn't start the animation again.

I'm trying to use this for a busy indicator so I'd like to bind to a viewmodel prop when the app is busy.  Do I need to do this another way?

**Comment by XamlFlair** [comment]
@jsinsel  thanks for the bug report. I will investigate this and get back to you once I have some news.

**Comment by XamlFlair** [comment]
@jsinsel I'm glad you brought this up. So the first answer to your issue, in order to keep the animation repeating, change your animation settings as such:

```xml
<xf:AnimationSettings x:Key="TestRotate"
		Easing="Cubic"
		EasingMode="EaseInOut"
		Kind="RotateFrom"
		Rotation="-360"
		Duration="2000" />
```

For the issue of stopping the animation, unfortunately that is not yet implemented. The initial goal of repeating animations was to "kick off" animations, but I have yet to put a mechanism in place for stopping one. That is now next on my to-do list and will let you know on its progress since I feel it's a necessity.

**Comment by jsinsel** [comment]
Thanks for the quick reply!

**Comment by XamlFlair** [comment]
@jsinsel  the latest update should help you. Using the latest version, if you pass a False value, the animation will complete its current iteration and then stop. If you have any issues please let me know.
