### ISSUE TITLE
Problem installing Nuget Package - XamlFlair.WPF

### ISSUE THREAD

**Issue by kurtisnet** [XamlFlair/XamlFlair#65]
Hi,

May I ask if XamlFlair.WPF works with WPF apps targetting .Net Framework 4.6.1?

I am facing issues installing XamlFlair.WPF nuget package where it fails with the following error message:

> Install failed. Rolling back...
Package 'XamlFlair.WPF.1.2.5 : Microsoft.Extensions.Logging.Abstractions [1.1.1, ), Microsoft.SourceLink.GitHub [1.0.0, ), System.Reactive [5.0.0, )' does not exist in project.

After the failure, I get this error message:

> Error		Could not install package 'XamlFlair.WPF 1.2.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.	

I would really love to integrate this awesome library into my project but failing to do so at the moment. Would you know what this would be happening?

**Comment by XamlFlair** [comment]
Hi @kurtisnet,

That would make sense, XamlFlair is currently targeting 4.7.2, Core 3.0 and 3.1:

`<TargetFrameworks>net472;netcoreapp3.0;netcoreapp3.1</TargetFrameworks>`

Do you plan on updating anytime soon? Another option would simply be I update the XF targets and include support for 4.6.1 and others (such as net48).

**Comment by kurtisnet** [comment]
Hi @XamlFlair, thank you for your reply. 

It's very challenging for us to target newer versions of .NET framework for our tools because some of the users (without admin rights to install .NET updates) are still on Windows 8.1 and our IT has still not pushed any newer framework versions to them :(

It would be really appreciated if you XamlFlair could also include support for 4.6.1 if compatibility with its features are not affected by doing so. Thank you once again.

**Comment by XamlFlair** [comment]
Ok, thanks for getting back to me. I'll try to update it soon enough and will let you know if it works 👍

**Comment by XamlFlair** [comment]
Hi @kurtisnet ,

Please go ahead and try XamlFlair.WPF 1.2.7, it should work for you. If you encounter an issue, please let me know.

**Comment by kurtisnet** [comment]
Hi @XamlFlair ,

Thank you very much for your quick support - I am happy to report that XamlFlair has installed successfully on a .NET Framework 4.6.1 WPF solution now.

Have a great day ahead and thanks again! :)
