### ISSUE TITLE
[Suggestion] Make easier to import DefaultAnimations.xaml

### ISSUE THREAD

**Issue by GF-Huang** [XamlFlair/XamlFlair#71]
Like [HandyControls](https://hosseini.ninja/handycontrol/quick_start/), it's very easy to import resources.

![image](https://user-images.githubusercontent.com/4510984/113332232-789c2600-9353-11eb-9d34-b54ec78ebd8a.png)

Make a class inherits `ResourceDictionary` that default `Source` is `pack://application:,,,/XamlFlair.WPF;component/DefaultAnimations.xaml` to make users easier import, rather than:
```xaml
<ResourceDictionary Source="pack://application:,,,/XamlFlair.WPF;component/DefaultAnimations.xaml"/>
```

**Comment by XamlFlair** [comment]
I like this idea. I'll note this down as an enhancement to be added. 👍

**Comment by assassin316** [comment]
@GF-Huang This has been completed and will be in the next version.

**Comment by GF-Huang** [comment]
I found that after change to `<xf:XamlFlairResources />`, the `{StaticResource xxx}` intellisense not works. 😅
