### ISSUE TITLE
AnimatedListView Compound Animations?

### ISSUE THREAD

**Issue by NickCaseG3r** [XamlFlair/XamlFlair#72]
Hi,

I'm trying to have an animation on a ListView when the ItemsSource changes, which moves the items off the screen one way, then the new items back onto the screen the other way, but when I try to set my:
```
  <xfc:AnimatedListView 
                xf:Animations.AnimateOnLoad="True"
                xf:Animations.AnimateOnItemsSourceChange="True"
                xf:Animations.Items="{xf:Animate BasedOn={StaticResource Compound}}">

</xfc:AnimatedListView>
```

I get the following error:

`XamlFlair.CompoundSettings is not a valid value for property 'Items'.
`

I can't find any documentation about Compound Settings explicitly not being supported by AnimatedListView, are they not?

**Comment by assassin316** [comment]
@NickCaseG3r Hi Nick, you're correct, they aren't supported. `Primary` and `Secondary` animations support an `IAnimationSettings` as opposed to `Items` which only supports an `AnimationSettings` object (due to the way it is handled internally).
