### ISSUE TITLE
Cannot use XamlFlair in Uno-Multi Platform Library

### ISSUE THREAD

**Issue by TopperDEL** [XamlFlair/XamlFlair#79]
I try to develop a controls-library for Uno Platform, where I want to take advantage of XamlFlair. But if I add The XamlFlair.Uno-Package (v1.2.6) to a Uno Multi Platform Library project, I get the error "Type or Namespace 'ComponentHolder' is not available in the namespace 'Windows.UI.Xaml.Markup'" (exact message may differ, this was translated from my german message).

Do you know what might cause that issue or how to solve it?

Steps to reproduce:
1. Create an Uno-App from the VS-template
2. Add a Uno Multi Platform Library
3. Add XamlFlair.Uno-Nuget
4. Reference the library from e.g. the UWP-Project
5. Build => it fails with that error.

Thank you!

**Comment by XamlFlair** [comment]
Hi, thanks for reporting the issue. I unfortunately can't reproduce the issue, Can you provide a sample solution with the issue and attach it here?

**Comment by TopperDEL** [comment]
Thank you for your quick reply! I just tried it on a different machine and I get the exact same error. You may have a look at [this](https://github.com/TopperDEL/uplink.NET.UnoHelpers) repo with the "XamlFalir-Error"-branch (which includes a typo :P).

I'm also attaching it here, so use what suits you best. Thank you!
[uplink.NET.UnoHelpers-XamlFalir-Error.zip](https://github.com/XamlFlair/XamlFlair/files/6675133/uplink.NET.UnoHelpers-XamlFalir-Error.zip)

**Comment by XamlFlair** [comment]
Very strange, I'm not able to compile your solution regardless of XamlFlair. Here's my test app:

[App1.zip](https://github.com/XamlFlair/XamlFlair/files/6679303/App1.zip)

**Comment by TopperDEL** [comment]
Did you try the main branch, too?
I'm on the go again. Will try you one asap.

**Comment by TopperDEL** [comment]
I had to change UAP from 17763 to 18362 in order to compile it on my system - then it worked. I did not yet find out what's wrong on my side.

I may try to start from scratch with my project. It seems to have something weird included. I'll lett you know how that goes and if it solves my issue. But it would still be interesting to see how that goes for you:
1. clone my repo
2. see if that builds
3. add XamlFlir-Nuget
4. see if that still builds

**Comment by assassin316** [comment]
Will do as soon as I get some free time. I had to bump the Uno UWP version not long ago, glad you found a fix.

**Comment by TopperDEL** [comment]
May you try adding a "Uno page" to the Classlibrary? If I do this with my newly created test project, I ran into similar issues together with XamlFlair.

**Comment by TopperDEL** [comment]
Yeah, simply adding a Page to the class-library-project breaks everything. Removing the XamlFlair-Reference afterwards makes it work again.

**Comment by TopperDEL** [comment]
Uh, and re-adding the package again makes it work again. What's happening here?

**Comment by assassin316** [comment]
Wow, that's strange indeed. Can it be an Uno issue?  I'll have to try this again to see if I can reproduce it.

**Comment by assassin316** [comment]
@TopperDEL  any update on this? Is it now working? I saw you mentioned in Discord that you got the library to work. Did it with with the XamlFlair library? Also note the new version that came out is against Uno 3.8.6 of you decide to use it.

**Comment by TopperDEL** [comment]
I just tried again, this time with the new 1.2.7 - and it's working as expected. Don't know, what that was as it happened on two different machines.
Well, let's take it like the physicist: "Must have been the air moisture..."

Thanks for the catch-up! Closing this issue.

**Comment by assassin316** [comment]
@TopperDEL  Glad to hear!
