### ISSUE TITLE
[Feature request ] Use ColorTo animation on border in WPF

### ISSUE THREAD

**Issue by xiejiang2014** [XamlFlair/XamlFlair#80]
XamlFlair.WPF 1.2.8

WPF XAML:

<Window
    x:Class="XamlFlairTry.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:xamlFlair="clr-namespace:XamlFlair;assembly=XamlFlair.WPF"
    Title="MainWindow"
    Width="800"
    Height="450"
    mc:Ignorable="d">

    <Window.Resources>
        <xamlFlair:AnimationSettings
            x:Key="SampleColorAnimation"
            ColorOn="Background"
            Delay="2000"
            Kind="ColorTo"
            Color="DarkGreen"
            Duration="5000" />
    </Window.Resources>

    <Border
        Width="100"
        Height="100"
        xamlFlair:Animations.Primary="{xamlFlair:Animate BasedOn={StaticResource ScaleFromLeft},
                                                         Duration=5000,
                                                         Delay=2000}"
        xamlFlair:Animations.Secondary="{StaticResource SampleColorAnimation}"
        Background="Brown" />

</Window>

**Expected behavior:**
Border's color animation can be executed normally 

**Actual behavior:**
it throw an exception :
System.ArgumentException:“$Cannot animate the ColorAnimation. Make sure the animation is applied on a Control, TextBlock, or Shape. Also make sure that an existing brush exists on the corresponding property (Background, Foreground, BorderBrush, Fill, or Stroke).”

**Comment by assassin316** [comment]
Thanks for the request. This will be easily added 👍

**Comment by assassin316** [comment]
@xiejiang2014 The change will be pushed within the next day or so, but just know that you can achieve the similar approach as such:

    <xamlFlair:AnimationSettings x:Key="ExpandAndColorAnimation"
                                        Kind="ScaleXFrom,ColorTo"
                                        ScaleX="0"
                                        ColorOn="Background"
                                        Color="Blue"
                                        TransformCenterPoint="0,0.5" />

    <Border Width="100"
            Height="100"
            xamlFlair:Animations.Primary="{xamlFlair:Animate BasedOn={StaticResource ExpandAndColorAnimation}, Duration=5000, Delay=2000}"
            Background="Red" />

**Comment by assassin316** [comment]
@xiejiang2014  you can get the latest version, it should work now 👍
