### ISSUE TITLE
Animation start with button click

### ISSUE THREAD

**Issue by volkankoc** [XamlFlair/XamlFlair#83]
How can I run animation on button click. Or how can I check?

**Comment by assassin316** [comment]
@volkankoc  Sorry for the delay. Are you trying to run an animation on the Button directly? Or did you want to trigger an animation on an Element that is not the Button?

**Comment by assassin316** [comment]
@volkankoc  Out of curiosity, what is your use case? Is it to trigger an animation on the button itself or on another element?

**Comment by volkankoc** [comment]
> @volkankoc Out of curiosity, what is your use case? Is it to trigger an animation on the button itself or on another element?

directly run with button

**Comment by assassin316** [comment]
@volkankoc  in that case, you'll need to trigger the animation with a Binding.

**Comment by volkankoc** [comment]
> @volkankoc in that case, you'll need to trigger the animation with a Binding.

ok thanks

**Comment by assassin316** [comment]
@volkankoc just an FYI for you, yesterday over started working on changes to support animations to run from any event. Therefore, for example, animating a button on its Click. I'll keep you posted when I get this changed included, it's something I've wanted to get done for awhile.

**Comment by volkankoc** [comment]
oh really. I would be very pleased. I am waiting.

**Comment by assassin316** [comment]
@volkankoc  you can grab the latest release, with that you can now do `Event=Click` on a button to animate it

**Comment by volkankoc** [comment]
> @volkankoc you can grab the latest release, with that you can now do `Event=Click` on a button to animate it
Sen harika adamsın. Çok teşekkürler
