### ISSUE TITLE
Any possible for adapting Avalonia

### ISSUE THREAD

**Issue by lsylusiyao** [XamlFlair/XamlFlair#84]
[Avalonia](https://github.com/AvaloniaUI/Avalonia) is a modernized version of WPF which moves WPF to *nix. Is there any possible adapting for this? Thanks.

**Comment by XamlFlair** [comment]
Do the controls used by Avalonia inherit from `FrameworkElement`? A lot of the animations in XamlFlair are based on `FrameworkElement`.

**Comment by lsylusiyao** [comment]
I've checked some of the code and it seems that, for Windows, it's inherited from `FrameworkElemet`, for *nix, there's a wrapper. Maybe it's possible, but still works to do :)

**Comment by XamlFlair** [comment]
Do you get errors when it compiles?

**Comment by lsylusiyao** [comment]
When I use this directly with both net5.0 and netcore3.1 , I received `Unable to resolve suitable regular or attached property Primary on type XamlFlair.WPF:XamlFlair.Animations` error. At least it can't use directly :(

**Comment by assassin316** [comment]
@lsylusiyao I've never tried Avalonia, can you create a sample project and attach it here so I can take a look?

**Comment by lsylusiyao** [comment]
This could be an example. 
[testAvalonia.zip](https://github.com/XamlFlair/XamlFlair/files/6753379/testAvalonia.zip)

**Comment by assassin316** [comment]
@lsylusiyao  After looking at some docs on Avalonia, this definitely wouldn't work with the XamlFlair.WPF package, it would definitely have to be a new package. I'll make note of this and  hopefully try to make some time for this in the near future.

**Comment by lsylusiyao** [comment]
It would be nice for Avalonia users. Thanks a lot.

**Comment by assassin316** [comment]
@lsylusiyao if do I get about doing so, I'll definitely do a Twitter blast about it :)
