### ISSUE TITLE
Problem installing nuget package for WPF

### ISSUE THREAD

**Issue by jg-cas** [XamlFlair/XamlFlair#91]
When installing the nuget package for WPF I get the following errors:

packages\Microsoft.Build.Tasks.Git.1.0.0\build\Microsoft.Build.Tasks.Git.targets(24,5): warning : Unable to locate repository with working directory that contains directory ;

packages\Microsoft.SourceLink.Common.1.0.0\build\Microsoft.SourceLink.Common.targets(52,5): warning : Source control information is not available - the generated source link is empty;

I researched extensively and tried all the fixes I could find, but no luck. I'm I doing something wrong or is there an issue with your nuget package? 

Thanks.

**Comment by XamlFlair** [comment]
Thanks for reporting this @jg-cas. What version of WPF are you trying it on? .Net Core? .Net Framework?

**Comment by jg-cas** [comment]
.Net Framework.

**Comment by XamlFlair** [comment]
@jg-cas  I was able to get this too, but it's simply a warning. I received this because my project was not linked to any Source Control. As well, it is just a warning and not an error, when I perform a Rebuild All, everything succeeds.

**Comment by jg-cas** [comment]
When I try your following example: 

<Border xf:Animations.Primary="{StaticResource FadeIn}" />
![Screenshot 2021-08-17 125409](https://user-images.githubusercontent.com/87249182/129791499-13c13b9c-2dd8-4287-b8c3-617ff2244796.png)


That static resource cannot be resolved and the program won't run. I only get intellisense for ResourceKey. Is this related or I am doing something else wrong?

**Comment by jg-cas** [comment]
I just figure there was no error. I did not created the resources library before trying out the animations. I appreciate your help and quick response!
