### ISSUE TITLE
AnimatedListView background turns white when other animations are playing

### ISSUE THREAD

**Issue by CodingOctocat** [XamlFlair/XamlFlair#94]
Is this an AnimatedListView feature or a bug?

**Comment by XamlFlair** [comment]
@CodingOctocat can you please provide some sample code? I'd like to see it happen.

**Comment by CodingOctocat** [comment]
> @CodingOctocat can you please provide some sample code? I'd like to see it happen.

The code is a bit long and looks roughly like this:
```XAML
<xfc:AnimatedListView Background="LightBlue"
    xf:Animations.InterElementDelay="50"
    xf:Animations.Items="{xf:Animate BasedOn={StaticResource FadeInAndSlideFromTop}, Delay=750}">
    <xfc:AnimatedListView.ItemTemplate>
        <-! Template with Style/DataTrigger ->
    <xfc:AnimatedListView.ItemTemplate>
</xfc:AnimatedListView>
```
`ListViewItem` triggers font size and opacity animations via `DataTrigger`.

There are other controls and animations in the window and I found that whenever an animation is played, the `Background` of the `AnimatedListView` turns `White`. After the animation is finished, the `Background` changes back to the set value.

**Comment by XamlFlair** [comment]
@CodingOctocat  thanks for the sample code, I will try this out soon enough and get back to you with my findings.

**Comment by XamlFlair** [comment]
@CodingOctocat  I'm having trouble reproducing the issue. I made my ListView brown, and it didn't change color. I also tried setting a color on my items, and still no luck. Would you be able to provide more info or more context on the issue? Can you maybe share some more Xaml that I can try?

**Comment by CodingOctocat** [comment]
> @CodingOctocat I'm having trouble reproducing the issue. I made my ListView brown, and it didn't change color. I also tried setting a color on my items, and still no luck. Would you be able to provide more info or more context on the issue? Can you maybe share some more Xaml that I can try?

I have a `Button` in my code, and when it is pressed, one of the items of the `AnimatedListView` will change (and trigger an animation with it), I debug and found that the `async void Button_Click` method has the `await Task.Delay()` statement, and when it is executed, the background of the `AnimatedListView` turns `White`, and the `Background` of the `AnimatedListView` turns to the set value only after the whole `Button_Click` method is executed.

I'm guessing the reason is asynchronous operation?

I tried to build a minimal case, but also trouble reproducing the issue😂

**Comment by CodingOctocat** [comment]
I'm stupid, I found the reason, because I set the `IsEnabled` property to the `AnimatedListView`, and it turns white when `IsEnabled=false`.

**Comment by XamlFlair** [comment]
@CodingOctocat  Glad to hear.👍😊

**Comment by CodingOctocat** [comment]
> @CodingOctocat Glad to hear.👍😊

Hi, I seem to have a new problem, if `IsEnabled=False`, then the `Background` of the `AnimatedListView` is always `White` and I can't change it via `Style`.

Did I make another mistake, or is it really a bug this time?

```XAML
<xfc:AnimatedListView.Style>
    <Style TargetType="xfc:AnimatedListView">
        <Style.Triggers>
            <Trigger Property="IsEnabled" Value="True">
                <Setter Property="Background" Value="Blue" />
            </Trigger>
            <Trigger Property="IsEnabled" Value="False">
                <Setter Property="Background" Value="Red" /> // Does not work!
            </Trigger>
        </Style.Triggers>
    </Style>
</xfc:AnimatedListView.Style>
```
