### ISSUE TITLE
The animation is only played for the first time

### ISSUE THREAD

**Issue by CodingOctocat** [XamlFlair/XamlFlair#95]
I have a `Border` and I control its `Visibility` property (toggle `Visible`/`Collapsed`) via shortcut keys.
I need the animation to play when I switch `Visibility` states(the initial value is `Collapsed`).
I found the animation(`Primary: FadeInAndSlideFromTop`) is only played for the first time(`Collapsed` -> `Visible`).

```XAML
<Border x:Name="myBorder"
        xf:Animations.CombinedBinding="{Binding Visibility, ElementName=myBorder, Converter={StaticResource VisibilityToBoolConverter}}"
        xf:Animations.Primary="{xf:Animate BasedOn={StaticResource FadeInAndSlideFromTop},
                                           Duration=200,
                                           Event=None}"
        xf:Animations.Secondary="{xf:Animate BasedOn={StaticResource FadeOutAndSlideToTop},
                                             Duration=200,
                                             Event=None}"
        Visibility="Collapsed"> 
</Border>
```

Is `XamlFlair` only suitable for entrance and exit animations? Is it difficult to express animations that need to be triggered by repeated switching in different states?

**Comment by XamlFlair** [comment]
It is possible to animate entrance and exit animations, but in your case, this won't work. How can you animate an Element when you set it to Collapsed? You can't. You will never see the animation because it immediately collapses. But you do see it when it becomes visible. Can you trigger the animation from a bool instead?

**Comment by XamlFlair** [comment]
I tried it with this:

    <StackPanel HorizontalAlignment="Center">
        <CheckBox x:Name="chk" />

        <Border x:Name="myBorder"
                Width="250"
                Height="250"
                Background="Red"
                xf:Animations.CombinedBinding="{Binding Visibility, ElementName=myBorder, Converter={StaticResource VisibilityToBoolConverter}}"
                xf:Animations.Primary="{xf:Animate BasedOn={StaticResource FadeInAndSlideFromTop},
                                        Duration=200,
                                        Event=None}"
                xf:Animations.Secondary="{xf:Animate BasedOn={StaticResource FadeOutAndSlideToTop},
                                            Duration=200,
                                            Event=None}"
                Visibility="{Binding ElementName=chk, Path=IsChecked}">
        </Border>
    </StackPanel>

**Comment by CodingOctocat** [comment]
> It is possible to animate entrance and exit animations, but in your case, this won't work. How can you animate an Element when you set it to Collapsed? You can't. You will never see the animation because it immediately collapses. But you do see it when it becomes visible. Can you trigger the animation from a bool instead?

But I only see the animation the first time it changes from the initial default `Collapsed` to `Visible`, when it `Collapsed` again and then becomes `Visible` again, I don't see the animation.

I want the animation to be triggered every time it becomes Visible.

I Tried:

```XAML
<Border x:Name="myBorder"
        xf:Animations.PrimaryBinding="{Binding Visibility, ElementName=myBorder, Converter={StaticResource VisibilityToBoolConverter}}"
        xf:Animations.Primary="{xf:Animate BasedOn={StaticResource FadeInAndSlideFromTop},
                                           Duration=200,
                                           Event=None}"
        Visibility="Collapsed"> 
</Border>
```
and:
```XAML
<Border x:Name="myBorder"
        xf:Animations.Primary="{xf:Animate BasedOn={StaticResource FadeInAndSlideFromTop},
                                           Duration=200,
                                           Event=Visibility}"
        Visibility="Collapsed"> 
</Border>
```

Both only play animations at the first `Visible`.

**Comment by assassin316** [comment]
Ok, so you can try this, it will animate the element when it becomes `Visible` (_keep in mind I'm using a `CheckBox` in my samples to simulate what you're doing in code-behind with `Visibility` changes_):

    <Page.Resources>
		<cnv:VisibilityToBoolConverter x:Key="VisibilityToBoolConverter" />
		<cnv:BoolToValueConverter x:Key="TrueToVisible"
								  TrueValue="Visible"
								  NullOrFalseValue="Collapsed" />
	</Page.Resources>

	<Grid Background="#294E90">
		<StackPanel HorizontalAlignment="Center" Width="250">
			<CheckBox x:Name="myCheck"
					  Content="Test" />

			<Border x:Name="myBorder"
					Width="250"
					Height="250"
					Background="Red"
					xf:Animations.Primary="{xf:Animate BasedOn={StaticResource FadeInAndSlideFromTop},
										   Duration=200,
										   Event=Visibility}"
					Visibility="{Binding ElementName=myCheck, Path=IsChecked, Converter={StaticResource TrueToVisible}}" />
		</StackPanel>
	</Grid>
	
If you want an exit animation, then it would have to trigger from a `bool` and not set a `Visibility` to `Collapsed:`

    <Page.Resources>
		<cnv:VisibilityToBoolConverter x:Key="VisibilityToBoolConverter" />
		<cnv:BoolToValueConverter x:Key="TrueToVisible"
								  TrueValue="Visible"
								  NullOrFalseValue="Collapsed" />
	</Page.Resources>

	<Grid Background="#294E90">
		<StackPanel HorizontalAlignment="Center" Width="250">
			<CheckBox x:Name="myCheck"
					  Content="Test"
					  IsChecked="False"/>

			<Border x:Name="myBorder"
					Width="250"
					Height="250"
					Background="Red"
					xf:Animations.CombinedBinding="{Binding ElementName=myCheck, Path=IsChecked}"
					xf:Animations.Primary="{xf:Animate BasedOn={StaticResource FadeInAndSlideFromRight},
										   Duration=200,
										   Event=None}"
					xf:Animations.Secondary="{xf:Animate BasedOn={StaticResource FadeOutAndSlideToRight},
										   Duration=200,
										   Event=None}"
					xf:Animations.StartWith="{StaticResource FadeOutAndSlideToRight}" />
		</StackPanel>
	</Grid>
	
Let me know your progress on this and if you still run into problems.

As well, if you see web animations that you're trying to simulate, can you share a gif of video here so I can determine if I can support it. Thanks! I would love to add features if I'm missing some.

**Comment by CodingOctocat** [comment]
@assassin316 Thank you for your reply, Some solutions on the Web also use `CheckBox`. Others seem to use `Attached Properties` that trigger the animation before Collapsed.

Back to the issue itself, I don't need an extra `CheckBox`, In terms of human thinking, we are more used to playing entry and exit animations based on the `Border`'s own `Visibility` state.

And your first case works the same way as mine (ie: it only plays an animation the first time it becomes `Visible`, the second and subsequent times when it becomes `Visible` again, it does not play the animation).

Your second case, it plays the entry and exit animations, but I have to press the shortcut key first (my behind code can toggle the `Visibility` of the `Border` by pressing the specified shortcut key) for your case to play the animation correctly, too puzzling😵.

**Comment by CodingOctocat** [comment]
Also, if my `Border` has 5 states to play animations (when `Visible`, `Collapsed`, `MouseOver`, `MouseDown`, `MouseUp`), is `XamlFlair` not able to meet my needs? Does `XamlFlair` only support at most two animations (`Primary` and `Secondary` animations)?

**Comment by assassin316** [comment]
@CodingOctocat  Sorry for the delay, I'm surprised the 1st case doesn't work for you, my animation (in WPF) is always animating, even after subsequent clicks of the checkbox.

As for the 2nd case, try removing the `StartWith` statement and see if that helps.

Concerning you question, unfortunately in XamlFlair I only support Primary and Secondary animations, and can only link one event per animation, therefore 2 animations. I built it this way because my intention was to have Primary and Secondary to be opposing animations.

However, multiple events can be linked together using containing elements, such as this very rough example:

    <Border xf:Animations.Primary="{xf:Animate BasedOn={StaticResource FadeOut}, Opacity=0.5, Event=PreviewMouseDown}"
				xf:Animations.Secondary="{xf:Animate BasedOn={StaticResource FadeIn}, Event=PreviewMouseUp}">
			<Button Content="Animation Test"
					Width="250"
					Height="40"
					xf:Animations.Primary="{xf:Animate BasedOn={StaticResource Shrink}, Event=MouseEnter, Duration=250}"
					xf:Animations.Secondary="{xf:Animate BasedOn={StaticResource Grow}, Event=MouseLeave, Duration=250}" />
    </Border>

**Comment by CodingOctocat** [comment]
@assassin316 thanks for your answer.

**Comment by assassin316** [comment]
@CodingOctocat  was the issue resolved? you were able to make it work?

**Comment by CodingOctocat** [comment]
> @CodingOctocat was the issue resolved? you were able to make it work?

No, I solved it with traditional animation, I just created a new empty WPF project again and copied 100% of your code (except for `BoolToVisibilityConverter`) and still have the same problem.

**Update**: I made a new discovery, I set the `Duration` property to `2000` (so I can observe) and I found that the second and subsequent `Visible` animations (`FadeInAndSlideFromTop) are triggered, but only the `FadeIn` effect is played and the `SlideFromTop` effect is lost.

**Comment by XamlFlair** [comment]
@CodingOctocat ahh, I'll try it out again and see what I get as a result. I'll keep you posted.

**Comment by assassin316** [comment]
@CodingOctocat  try this:

Declare this in your page resources and use it instead of `FadeInAndSlideFromTop`:

    <xf:CompoundSettings x:Key="FadeInAndSlideFromTopSequence"> 
        <xf:CompoundSettings.Sequence>
            <xf:AnimationSettings Kind="FadeTo,TranslateYTo"
                                    Opacity="0"
                                    OffsetY="{StaticResource NegativeOffset}"
                                    Duration="1"/>
            <xf:AnimationSettings Kind="FadeFrom,TranslateYFrom"
                                    Opacity="0"
                                    OffsetY="{StaticResource NegativeOffset}" />
        </xf:CompoundSettings.Sequence>
    </xf:CompoundSettings>
    
Let me know because I'm curious to know if this works.

**Comment by CodingOctocat** [comment]
@assassin316 `FadeInAndSlideFromTopSequence` work well!, But why doesn't `FadeInAndSlideFromTop` work? Isn't its internal implementation the same as `FadeInAndSlideFromTopSequence`?

**Comment by assassin316** [comment]
@CodingOctocat I FINALLY was able to reproduce it as in your case, with a KeyDown on a window to trigger the `FadeInAndSlideFromTop` animation. I get the `FadeIn` but not subsequent `FadeInAndSlideFromTop`. I'll investigate and report back.

**Comment by XamlFlair** [comment]
@CodingOctocat  thank you for reporting this issue. I did in fact find a bug in which the Transform itself was not updating the Y translation after it was being set. Go ahead and get the latest version and try it, your issue should be fixed with version 1.2.13

**Comment by CodingOctocat** [comment]
@XamlFlair Thanks, I tested the 1.2.13 and it worked fine.

**Comment by zaitsman** [comment]
@assassin316 
I tried to adapt your snippet :

> 				xf:Animations.CombinedBinding="{Binding ElementName=myCheck, Path=IsChecked}"
> 				xf:Animations.Primary="{xf:Animate BasedOn={StaticResource FadeInAndSlideFromRight},
> 									   Duration=200,
> 									   Event=None}"
> 				xf:Animations.Secondary="{xf:Animate BasedOn={StaticResource FadeOutAndSlideToRight},
> 									   Duration=200,
> 									   Event=None}"
> 				xf:Animations.StartWith="{StaticResource FadeOutAndSlideToRight}" />

Like so:

 ```
<Rectangle
           xf:Animations.CombinedBinding="{Binding ElementName=mainWindow, Path=DataContext.IsVisible}"
				xf:Animations.Primary="{xf:Animate BasedOn={StaticResource FadeIn},
									   Duration=15000,
									   Event=None}"
				xf:Animations.Secondary="{xf:Animate BasedOn={StaticResource FadeOut},
									   Duration=15000,
									   Event=None}"
				xf:Animations.StartWith="{StaticResource FadeOut}"
                Fill="Red"
                Grid.Row="1"
            ></Rectangle>
```

This is in WPF with .net 6.

The FadeIn animation plays, but FadeOut doesn't, the Rectangle instantly disappears :(
