### ISSUE TITLE
When the AnimatedListView is collapsed and expanded again, the ListViewItem state is reset

### ISSUE THREAD

**Issue by CodingOctocat** [XamlFlair/XamlFlair#98]
I have an `AnimatedListView` and I need item to `FadeOut` when "SampleData.IsFoo == True" and `FadeIn` when it goes back to "False".

Let's say that some of the data is now in the `FadedOut(Opacity=0.2)` state. Then when I drag the `GridSplitter` to the top, the `AnimatedListView` is collapsed, then I drag the `GridSplitter` to the bottom and the faded `ListViewItem` returns to its normal state (`Opacity=1`), i.e., I tried the traditional `DataTrigger+ Storyboard` mode, which reapplies the animation when the `AnimatedListView` resumes Expanded/Visible.

In other words, `XamlFlair` should reapply the animation when the element shows _disappear_ and then _appears_.

P.S: I haven't tested `ListView` for this issue, I think `AnimatedListView` should not be different from `ListView` in this issue.

```XAML
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="*" />
        <RowDefinition Height="Auto" />
        <RowDefinition Height="50" />
    </Grid.RowDefinitions>

    <xfc:AnimatedListView ItemsSource="{Binding SampleDataList}"
                          xf:Animations.Items="{StaticResource FadeInAndSlideFromTop}">
        <xfc:AnimatedListView.ItemContainerStyle>
            <Style TargetType="{x:Type ListViewItem}">
                <Setter Property="Template">
                    <Setter.Value>
                        <ControlTemplate TargetType="{x:Type ListViewItem}">
                            <Border Background="Blue"
                                xf:Animations.AllowOpacityReset="False"
                                xf:Animations.CombinedBinding="{Binding IsFoo}"
                                xf:Animations.Primary="{xf:Animate BasedOn={StaticResource FadeOut},
                                   Opacity=0.2,
                                   Duration=1000,
                                   Delay=1000}"
                                xf:Animations.Secondary="{xf:Animate BasedOn={StaticResource FadeIn},
                                     Duration=1000,
                                     Opacity=1}" >
                                 <TextBlock Text="{Binding Bar}" />
                            </Border>
            </Style>
        </xfc:AnimatedListView.ItemContainerStyle>

    <GridSplitter Grid.Row="1"
              Height="2"
              HorizontalAlignment="Stretch"
              VerticalAlignment="Center"
              Background="LightGray" />

    <Border Grid.Row="2" />
</Grid>
```
```CSharp
public class SampleData
{
    public string Bar { get; set; }
    public string IsFoo { get; set; }
}
```

**Comment by XamlFlair** [comment]
@CodingOctocat  let me try this code as soon as I can and I'll see what happens.

**Comment by CodingOctocat** [comment]
@XamlFlair 
Hi, in simple terms, if some items of the `ListView` have become `Opacity=0.2` (through xf animation), then resize of the `ListView` to 0, and then resize to the `ListView` again to expand, items of `Opacity` value reverted to 1. 
If I use `DataTrigger` it won't be like this.
